/*
 * This source file was generated by the Gradle 'init' task
 */

package edu.ukma.smart.virtual;

import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.Properties;

import org.testcontainers.containers.GenericContainer;
import org.testng.annotations.AfterClass;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeClass;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

public class DefaultVirtualTableServiceTest {

    private static final String DB_NAME = "test_db";

    private GenericContainer<?> container;

    @BeforeClass
    public void setUp() throws InterruptedException {
        container = new GenericContainer<>("postgres:latest")
            .withExposedPorts(5432)
            .withEnv("POSTGRES_PASSWORD", "test");
        container.start();
    }

    @AfterClass
    public void tearDown() {
        container.stop();
    }

    @BeforeMethod
    public void init() throws IOException, InterruptedException {
        container.execInContainer("psql", "-U", "postgres", "-c", "CREATE DATABASE %s;".formatted(DB_NAME));
    }

    @AfterMethod
    public void cleanUp() throws IOException, InterruptedException {
        container.execInContainer("psql", "-U", "postgres", "-c", "DROP DATABASE IF EXISTS %s;".formatted(DB_NAME));
    }

    @Test
    public void testLibConnection() throws SQLException {
        String url = "jdbc:postgresql://localhost:%d/%s".formatted(container.getMappedPort(5432), DB_NAME);
        Properties props = new Properties();
        props.setProperty("user", "postgres");
        props.setProperty("password", "test");
        Connection conn = DriverManager.getConnection(url, props);

        var service = new DefaultVirtualTableService(conn);
        service.deleteTable("table_key");
    }
}
