name: Deploy

on:
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Release
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: lib.jar
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: lib.jar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
